import { StyleSheet } from "react-native";

/**
 * # Shared Screen Styles
 *
 * ## Business Value & Purpose
 * The five deck screens share one visual language — the same panel silhouettes, the same
 * gutters, the same slab proportions. Keeping their styles together is what makes them
 * read as one instrument rather than five apps stapled together: a change to the
 * console's look happens in one place instead of five.
 *
 * This is deliberately *not* a per-screen split. Duplicating these declarations across
 * five files would let the screens drift apart silently, which is the exact failure this
 * sheet prevents. What was split out of the old 1,385-line `screens.tsx` was the
 * *markup* — the part that genuinely differs per screen.
 */
export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { paddingHorizontal: 16, paddingBottom: 42 },
  pressed: { opacity: 0.72, transform: [{ scale: 0.99 }] },
  intro: { fontSize: 15, lineHeight: 22, marginHorizontal: 3, marginBottom: 4 },
  continuePanel: {
    minHeight: 235,
    borderRadius: 20,
    borderWidth: 1,
    padding: 20,
    overflow: "hidden",
  },
  continueRail: { position: "absolute", left: 0, top: 0, bottom: 0, width: 9 },
  kicker: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "900",
    letterSpacing: 1.3,
  },
  heroTitle: {
    fontSize: 27,
    lineHeight: 34,
    fontWeight: "800",
    letterSpacing: -0.9,
    marginTop: 17,
    maxWidth: "94%",
  },
  heroMeta: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginTop: 7,
  },
  beginButton: {
    minHeight: 62,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 20,
    marginTop: 22,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 11,
  },
  beginGlyph: { fontSize: 19, fontWeight: "900" },
  beginText: { fontSize: 17, fontWeight: "800" },
  pendingPanel: {
    minHeight: 68,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 12,
  },
  pendingCopy: { marginLeft: 13, flex: 1 },
  pendingTitle: { fontSize: 14, fontWeight: "700" },
  pendingMeta: { marginTop: 2, fontSize: 11 },
  pendingAction: {
    minWidth: 48,
    minHeight: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  pendingActionText: { fontSize: 9, fontWeight: "900" },
  quickGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  quickAction: {
    width: "48%",
    minHeight: 87,
    borderRadius: 13,
    borderWidth: 1,
    padding: 14,
    justifyContent: "space-between",
  },
  quickCode: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1 },
  quickLabel: { fontSize: 15, fontWeight: "700" },
  activityRow: {
    minHeight: 52,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  activityCode: {
    width: 54,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  activityText: { flex: 1, fontSize: 14, fontWeight: "600" },
  spaceStatus: {
    minHeight: 88,
    borderRadius: 14,
    borderWidth: 1,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
    marginTop: 3,
  },
  compactButton: {
    minHeight: 48,
    minWidth: 79,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },
  compactButtonText: { fontSize: 14, fontWeight: "800" },
  chipRow: { paddingRight: 12 },
  modeRow: { flexDirection: "row", gap: 7 },
  modeButton: {
    flex: 1,
    minHeight: 47,
    borderRadius: 9,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modeText: { fontSize: 11, fontWeight: "900", letterSpacing: 0.8 },
  overview: { borderRadius: 15, borderWidth: 1, padding: 17, marginTop: 13 },
  overviewText: { fontSize: 19, fontWeight: "700", marginTop: 8 },
  overviewMeta: { fontSize: 11, marginTop: 6 },
  discussPanel: {
    borderWidth: 1,
    borderRadius: 15,
    padding: 17,
    marginTop: 13,
  },
  discussTitle: { fontSize: 20, fontWeight: "800" },
  discussBody: { fontSize: 14, lineHeight: 20, marginTop: 6 },
  studyCommands: { marginTop: 13 },
  commandSlab: {
    minHeight: 62,
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  commandCode: {
    width: 65,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  commandTitle: { flex: 1, fontSize: 15, fontWeight: "700" },
  commandArrow: { fontSize: 15, fontWeight: "900" },
  contextPanel: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginBottom: 13,
  },
  contextTitle: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    marginBottom: 9,
  },
  intentGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 8 },
  terminal: {
    minHeight: 330,
    borderRadius: 17,
    borderWidth: 1,
    marginTop: 17,
    padding: 16,
  },
  terminalHead: { flexDirection: "row", justifyContent: "space-between" },
  terminalMode: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1 },
  terminalCursor: { fontSize: 10 },
  terminalInput: {
    minHeight: 180,
    textAlignVertical: "top",
    fontSize: 17,
    lineHeight: 26,
    paddingTop: 22,
    paddingHorizontal: 0,
  },
  routeButton: {
    minHeight: 58,
    borderRadius: 11,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  routeGlyph: { fontSize: 18, fontWeight: "900" },
  routeText: { fontSize: 16, fontWeight: "800" },
  commandHelp: { fontSize: 13, lineHeight: 24, letterSpacing: 0.3 },
  commandHint: { fontSize: 13, lineHeight: 19, marginTop: 5 },
  empty: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 13,
    padding: 22,
    alignItems: "center",
  },
  emptyCode: { fontSize: 10, fontWeight: "800", letterSpacing: 1 },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    marginTop: 7,
  },
});
